### PR TITLE
Remove facades from service provider

### PR DESCRIPTION
**Pull request by joecohens**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This change was already made on 3.0.

**Comment by joecohens** [comment]
But 3.0 it's only for L5 right?

**Comment by GrahamCampbell** [comment]
Yeh. It contains many improvements. Remember I said we supported dependency injection. What I should have said was the new L5 version supports dependency injection.

**Comment by GrahamCampbell** [comment]
Giving travis a kick...

**Comment by joecohens** [comment]
Yeah that's what I thought :) this package for L5 it's super cool!

**Comment by GrahamCampbell** [comment]
Meh, merging. I don't think the tests even cover this on 2.x.

**Comment by joecohens** [comment]
Haha thanks!

**Comment by GrahamCampbell** [comment]
I'll tag another 2.2.x release as soon as travis is passing. :)

**Comment by GrahamCampbell** [comment]
Just re-run travis, and we're green on 2.2.

**Comment by GrahamCampbell** [comment]
Tagged 2.2.2: https://github.com/ShawnMcCool/laravel-auto-presenter/releases/tag/2.2.2.

**Comment by joecohens** [comment]
Awesome thanks!

**Comment by GrahamCampbell** [comment]
I'm running composer update on cachet as we speak. :)

**Comment by joecohens** [comment]
:)

**Pull request merged**
