### PR TITLE
let presenter decorators be aware of "themselves" (redo)

### PR DESCRIPTION
**Pull request by devinfd**
* apologies, didn't run test prior to original commit

ref: https://github.com/ShawnMcCool/laravel-auto-presenter/pull/72

### CODE REVIEW

**Comment by devinfd** [comment]
I don't understand, the tests pass on my machine... Regardless I hope this idea is considered in the future.

**Comment by GrahamCampbell** [comment]
property_exists won't work on actual eloquent models.

**Comment by GrahamCampbell** [comment]
this makes no sense anyway, you can just make function calls on the underlying object yourself anyway?

**Comment by GrahamCampbell** [comment]
the wrapped object is already passed to the presenter...

**Comment by devinfd** [comment]
"the wrapped object is already passed to the presenter..."
- I want to present the attribute not the object. Also, In the case of a date attribute, converting it to a carbon object in the presenter seems redundant if I've already mutated the attribute as a date in the model.

"this makes no sense anyway, you can just make function calls on the underlying object yourself anyway?"
- Yes I could do getPublishedAtAttribute($value) in the model but that's kinda gross and I'd rather keep presentation out of the model. Hence the reason for this package.

Just my feedback.

**Comment by GrahamCampbell** [comment]
Sorry, but I'm confused as to what you are actually trying to do? Could you provide a really small code sample?

**Comment by devinfd** [comment]
```php
class Post extends Model implements HasPresenter {
    `other model stuff`

    protected $dates = [
        'published_at'
    ];

    public function getPresenterClass()
    {
        return PostPresenter::class;
    }
}

class PostPresenter extends BasePresenter {

    public function __construct(Post $resource)
    {
        $this->wrappedObject = $resource;
    }

    public function published_at()
    {
        return $this->wrappedObject->published_at->format('n/j/Y');
    }

    // VS
    //public function published_at($self)
    //{
    //     return $self->format('n/j/Y');
    //}
 
}
```
There's really nothing wrong with the above code except that the `$this->wrappedObject->published_at` feels redundant being that it is in the `published_at` method. `$self->format('n/j/Y');` seems more intuitive. Passing the wrappedObject in the constructor is certainly useful if your decorator needs to be more aware of other attribute values, but for simple decorators I think passing a reference to itself would be nice.

**Comment by GrahamCampbell** [comment]
The current method looks totally fine imo.

**Comment by devinfd** [comment]
ok

**Pull request closed without merging**
